export const GET_DECK_ASYNC = 'GET_DECK_ASYNC'
export const GET_DECKS_ASYNC = 'GET_DECKS_ASYNC'
export const ERROR_DECK_ASYNC = 'ERROR_DECK_ASYNC'
export const ERROR_DECKS_ASYNC = 'ERROR_DECKS_ASYNC'